#PANDAS

In [ ]:
import pandas as pd

In [ ]:
sozluk={"ISIM":["Mete","Ferhat","Buket","Batu","Rabiye","Buğrahan"],
        "YAS":[40,45,30,35,30,28],
        "MAAS":[10000,15000,20000,25000,30000,35000]}

In [ ]:
sozluk

{'ISIM': ['Mete', 'Ferhat', 'Buket', 'Batu', 'Rabiye', 'Buğrahan'],
 'YAS': [40, 45, 30, 35, 30, 28],
 'MAAS': [10000, 15000, 20000, 25000, 30000, 35000]}

In [ ]:
data=pd.DataFrame(sozluk)

In [ ]:
data.head() # ilk 5 veriyi getirir.

     ISIM  YAS   MAAS
0    Mete   40  10000
1  Ferhat   45  15000
2   Buket   30  20000
3    Batu   35  25000
4  Rabiye   30  30000

In [ ]:
data.head(3) # Icine deger verirsek o deger kadar veri getirir.

     ISIM  YAS   MAAS
0    Mete   40  10000
1  Ferhat   45  15000
2   Buket   30  20000

In [ ]:
data.tail() # Son 5 veriyi getirir.

       ISIM  YAS   MAAS
1    Ferhat   45  15000
2     Buket   30  20000
3      Batu   35  25000
4    Rabiye   30  30000
5  Buğrahan   28  35000

In [ ]:
data.columns # Kolon isimlerini getirir.

Index(['ISIM', 'YAS', 'MAAS'], dtype='object')

In [ ]:
data.info() # Veri hakkinda detayli bilgi verir.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ISIM    6 non-null      object
 1   YAS     6 non-null      int64
 2   MAAS    6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes

In [ ]:
data.dtypes # Verilerin tiplerini dondurur.

ISIM    object
YAS      int64
MAAS     int64
dtype: object

In [ ]:
data.describe()  # Verilerdeki bazi yapmak isteyecegimiz hesaplari dondurur.

             YAS          MAAS
count   6.000000      6.000000
mean   34.666667  22500.000000
std     6.683313   9354.143467
min    28.000000  10000.000000
25%    30.000000  16250.000000
50%    32.500000  22500.000000
75%    38.750000  28750.000000
max    45.000000  35000.000000

In [ ]:
data.describe().T  # Tabloyu cevirir.

,count,mean,std,min,25%,50%,75%,max
YAS,6.0,34.666667,6.683313,28.0,30.0,32.5,38.75,45.0
MAAS,6.0,22500.000000,9354.143467,10000.0,16250.0,22500.0,28750.00,35000.0

In [ ]:
data.shape

(6, 3)

In [ ]:
data.YAS

0    40
1    45
2    30
3    35
4    30
5    28
Name: YAS, dtype: int64

In [ ]:
data["YAS"]

0    40
1    45
2    30
3    35
4    30
5    28
Name: YAS, dtype: int64

In [ ]:
data["AGNO"]=[3.40,3,2.66,2.88,2,2.1]

In [ ]:
data

       ISIM  YAS   MAAS  AGNO
0      Mete   40  10000  3.40
1    Ferhat   45  15000  3.00
2     Buket   30  20000  2.66
3      Batu   35  25000  2.88
4    Rabiye   30  30000  2.00
5  Buğrahan   28  35000  2.10

In [ ]:
data["AGNO1"]=[3.40,3,2.66,2.88,2] # pandasta sozlukle islem yaptigimiz icin eksik veri giremiyoz.

ValueError: Length of values (5) does not match length of index (6)

In [ ]:
data

       ISIM  YAS   MAAS  AGNO
0      Mete   40  10000  3.40
1    Ferhat   45  15000  3.00
2     Buket   30  20000  2.66
3      Batu   35  25000  2.88
4    Rabiye   30  30000  2.00
5  Buğrahan   28  35000  2.10

In [ ]:
data.loc[:,"YAS"] # loc ta ilk deger satir ikinci deger sutun yani burda tüm satirlari sec ama sadece yas sutununu al diyor.

0    40
1    45
2    30
3    35
4    30
5    28
Name: YAS, dtype: int64

In [ ]:
data.loc[:3,"YAS"] # 3 te dahil.!!

0    40
1    45
2    30
3    35
Name: YAS, dtype: int64

In [ ]:
data.loc[:3,"YAS":"AGNO"]

   YAS   MAAS  AGNO
0   40  10000  3.40
1   45  15000  3.00
2   30  20000  2.66
3   35  25000  2.88

In [ ]:
data[::-1]

       ISIM  YAS   MAAS  AGNO
5  Buğrahan   28  35000  2.10
4    Rabiye   30  30000  2.00
3      Batu   35  25000  2.88
2     Buket   30  20000  2.66
1    Ferhat   45  15000  3.00
0      Mete   40  10000  3.40

In [ ]:
data.loc[::-1,::-1]

   AGNO   MAAS  YAS      ISIM
5  2.10  35000   28  Buğrahan
4  2.00  30000   30    Rabiye
3  2.88  25000   35      Batu
2  2.66  20000   30     Buket
1  3.00  15000   45    Ferhat
0  3.40  10000   40      Mete

In [ ]:
filtre1=data.YAS>30
yeniData=data[filtre1]
yeniData

     ISIM  YAS   MAAS  AGNO
0    Mete   40  10000  3.40
1  Ferhat   45  15000  3.00
3    Batu   35  25000  2.88

In [ ]:
filtre2=data.MAAS>10000
yeniData=data[filtre1 & filtre2]
yeniData

     ISIM  YAS   MAAS  AGNO
1  Ferhat   45  15000  3.00
3    Batu   35  25000  2.88

In [ ]:
data["Durum"]=["Gecti" if i>=3 else "Kaldi" for i in data.AGNO]
data

       ISIM  YAS   MAAS  AGNO  Durum
0      Mete   40  10000  3.40  Gecti
1    Ferhat   45  15000  3.00  Gecti
2     Buket   30  20000  2.66  Kaldi
3      Batu   35  25000  2.88  Kaldi
4    Rabiye   30  30000  2.00  Kaldi
5  Buğrahan   28  35000  2.10  Kaldi

In [ ]:
ortalamaAgno=data.AGNO.mean()
ortalamaAgno

np.float64(2.673333333333334)

In [ ]:
data["Sonuc"]=["Gecti" if i>ortalamaAgno else "Kaldi" for i in data.AGNO]
data

       ISIM  YAS   MAAS  AGNO  Durum  Sonuc
0      Mete   40  10000  3.40  Gecti  Gecti
1    Ferhat   45  15000  3.00  Gecti  Gecti
2     Buket   30  20000  2.66  Kaldi  Kaldi
3      Batu   35  25000  2.88  Kaldi  Gecti
4    Rabiye   30  30000  2.00  Kaldi  Kaldi
5  Buğrahan   28  35000  2.10  Kaldi  Kaldi

In [ ]:
data.drop(["Durum"],axis=1)

       ISIM  YAS   MAAS  AGNO  Sonuc
0      Mete   40  10000  3.40  Gecti
1    Ferhat   45  15000  3.00  Gecti
2     Buket   30  20000  2.66  Kaldi
3      Batu   35  25000  2.88  Gecti
4    Rabiye   30  30000  2.00  Kaldi
5  Buğrahan   28  35000  2.10  Kaldi

In [ ]:
data

       ISIM  YAS   MAAS  AGNO  Durum  Sonuc
0      Mete   40  10000  3.40  Gecti  Gecti
1    Ferhat   45  15000  3.00  Gecti  Gecti
2     Buket   30  20000  2.66  Kaldi  Kaldi
3      Batu   35  25000  2.88  Kaldi  Gecti
4    Rabiye   30  30000  2.00  Kaldi  Kaldi
5  Buğrahan   28  35000  2.10  Kaldi  Kaldi

In [ ]:
data=data.drop(["Durum"],axis=1)
data

       ISIM  YAS   MAAS  AGNO  Sonuc
0      Mete   40  10000  3.40  Gecti
1    Ferhat   45  15000  3.00  Gecti
2     Buket   30  20000  2.66  Kaldi
3      Batu   35  25000  2.88  Gecti
4    Rabiye   30  30000  2.00  Kaldi
5  Buğrahan   28  35000  2.10  Kaldi

In [ ]:
data["Sonuc1"]=["Gecti" if i>ortalamaAgno else "Kaldi" for i in data.AGNO]
data

       ISIM  YAS   MAAS  AGNO  Sonuc Sonuc1
0      Mete   40  10000  3.40  Gecti  Gecti
1    Ferhat   45  15000  3.00  Gecti  Gecti
2     Buket   30  20000  2.66  Kaldi  Kaldi
3      Batu   35  25000  2.88  Gecti  Gecti
4    Rabiye   30  30000  2.00  Kaldi  Kaldi
5  Buğrahan   28  35000  2.10  Kaldi  Kaldi

In [ ]:
data.drop(["Sonuc1"],axis=1,inplace=True)
data

       ISIM  YAS   MAAS  AGNO  Sonuc
0      Mete   40  10000  3.40  Gecti
1    Ferhat   45  15000  3.00  Gecti
2     Buket   30  20000  2.66  Kaldi
3      Batu   35  25000  2.88  Gecti
4    Rabiye   30  30000  2.00  Kaldi
5  Buğrahan   28  35000  2.10  Kaldi

In [ ]:
import numpy as np

In [ ]:
data=pd.DataFrame(np.random.randn(6,6),
                  index=["Mete","Ferhat","Buket","Batu","Rabiye","Buğrahan"],
                  columns=["CRP","ALT","AST","P","Na","Glukoz"])
data

               CRP       ALT       AST         P        Na    Glukoz
Mete      0.268619 -1.361207  2.621280 -0.574841  1.067038  0.532204
Ferhat   -0.420208 -0.751461 -1.209858  0.637792 -1.615432  0.929646
Buket    -1.527151  1.055574  1.813520 -0.293038 -0.928135 -0.876224
Batu      1.090813 -1.133370 -0.908228 -0.913795 -0.947229  2.193338
Rabiye   -0.385224 -1.248910  0.027381 -0.981071 -0.234963 -1.049492
Buğrahan  0.416478 -0.249212  0.066971 -0.045529 -0.425816  1.062383

In [ ]:
data.loc["Buket":"Rabiye","ALT":"Na"]=np.nan
data

               CRP       ALT       AST         P        Na    Glukoz
Mete      0.268619 -1.361207  2.621280 -0.574841  1.067038  0.532204
Ferhat   -0.420208 -0.751461 -1.209858  0.637792 -1.615432  0.929646
Buket    -1.527151       NaN       NaN       NaN       NaN -0.876224
Batu      1.090813       NaN       NaN       NaN       NaN  2.193338
Rabiye   -0.385224       NaN       NaN       NaN       NaN -1.049492
Buğrahan  0.416478 -0.249212  0.066971 -0.045529 -0.425816  1.062383

In [ ]:
data.isnull() # NaN olanlar True dondurur.

            CRP    ALT    AST      P     Na  Glukoz
Mete      False  False  False  False  False   False
Ferhat    False  False  False  False  False   False
Buket     False   True   True   True   True   False
Batu      False   True   True   True   True   False
Rabiye    False   True   True   True   True   False
Buğrahan  False  False  False  False  False   False

In [ ]:
data.isnull().sum()

CRP       0
ALT       3
AST       3
P         3
Na        3
Glukoz    0
dtype: int64

In [ ]:
data.isnull().sum().sum()

np.int64(12)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Mete to Buğrahan
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CRP     6 non-null      float64
 1   ALT     3 non-null      float64
 2   AST     3 non-null      float64
 3   P       3 non-null      float64
 4   Na      3 non-null      float64
 5   Glukoz  6 non-null      float64
dtypes: float64(6)
memory usage: 508.0+ bytes

In [ ]:
data.fillna(value=3.568) # NaN degerleri istedigimiz bir degerle doldurur.

               CRP       ALT       AST         P        Na    Glukoz
Mete      0.268619 -1.361207  2.621280 -0.574841  1.067038  0.532204
Ferhat   -0.420208 -0.751461 -1.209858  0.637792 -1.615432  0.929646
Buket    -1.527151  3.568000  3.568000  3.568000  3.568000 -0.876224
Batu      1.090813  3.568000  3.568000  3.568000  3.568000  2.193338
Rabiye   -0.385224  3.568000  3.568000  3.568000  3.568000 -1.049492
Buğrahan  0.416478 -0.249212  0.066971 -0.045529 -0.425816  1.062383

In [ ]:
data

               CRP       ALT       AST         P        Na    Glukoz
Mete      0.268619 -1.361207  2.621280 -0.574841  1.067038  0.532204
Ferhat   -0.420208 -0.751461 -1.209858  0.637792 -1.615432  0.929646
Buket    -1.527151       NaN       NaN       NaN       NaN -0.876224
Batu      1.090813       NaN       NaN       NaN       NaN  2.193338
Rabiye   -0.385224       NaN       NaN       NaN       NaN -1.049492
Buğrahan  0.416478 -0.249212  0.066971 -0.045529 -0.425816  1.062383

In [ ]:
data.fillna(value=1,inplace=True)

In [ ]:
data

               CRP       ALT       AST         P        Na    Glukoz
Mete      0.268619 -1.361207  2.621280 -0.574841  1.067038  0.532204
Ferhat   -0.420208 -0.751461 -1.209858  0.637792 -1.615432  0.929646
Buket    -1.527151  1.000000  1.000000  1.000000  1.000000 -0.876224
Batu      1.090813  1.000000  1.000000  1.000000  1.000000  2.193338
Rabiye   -0.385224  1.000000  1.000000  1.000000  1.000000 -1.049492
Buğrahan  0.416478 -0.249212  0.066971 -0.045529 -0.425816  1.062383

In [ ]:
data.loc["Buket":"Rabiye","ALT":"Na"]=np.nan
data

               CRP       ALT       AST         P        Na    Glukoz
Mete      0.268619 -1.361207  2.621280 -0.574841  1.067038  0.532204
Ferhat   -0.420208 -0.751461 -1.209858  0.637792 -1.615432  0.929646
Buket    -1.527151       NaN       NaN       NaN       NaN -0.876224
Batu      1.090813       NaN       NaN       NaN       NaN  2.193338
Rabiye   -0.385224       NaN       NaN       NaN       NaN -1.049492
Buğrahan  0.416478 -0.249212  0.066971 -0.045529 -0.425816  1.062383

In [ ]:
data.fillna(method="ffill") # NaN degerin ust kismindaki degeri NaN lara uygular.

/tmp/ipython-input-530333133.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method="ffill") # NaN degerin ust kismindaki degeri NaN lara uygular.

               CRP       ALT       AST         P        Na    Glukoz
Mete      0.268619 -1.361207  2.621280 -0.574841  1.067038  0.532204
Ferhat   -0.420208 -0.751461 -1.209858  0.637792 -1.615432  0.929646
Buket    -1.527151 -0.751461 -1.209858  0.637792 -1.615432 -0.876224
Batu      1.090813 -0.751461 -1.209858  0.637792 -1.615432  2.193338
Rabiye   -0.385224 -0.751461 -1.209858  0.637792 -1.615432 -1.049492
Buğrahan  0.416478 -0.249212  0.066971 -0.045529 -0.425816  1.062383

In [ ]:
data.fillna(method="bfill") # NaN degerin alt kismindaki degeri NaN lara uygular.

/tmp/ipython-input-2105753462.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method="bfill") # NaN degerin alt kismindaki degeri NaN lara uygular.

               CRP       ALT       AST         P        Na    Glukoz
Mete      0.268619 -1.361207  2.621280 -0.574841  1.067038  0.532204
Ferhat   -0.420208 -0.751461 -1.209858  0.637792 -1.615432  0.929646
Buket    -1.527151 -0.249212  0.066971 -0.045529 -0.425816 -0.876224
Batu      1.090813 -0.249212  0.066971 -0.045529 -0.425816  2.193338
Rabiye   -0.385224 -0.249212  0.066971 -0.045529 -0.425816 -1.049492
Buğrahan  0.416478 -0.249212  0.066971 -0.045529 -0.425816  1.062383

In [ ]:
data

               CRP       ALT       AST         P        Na    Glukoz
Mete      0.268619 -1.361207  2.621280 -0.574841  1.067038  0.532204
Ferhat   -0.420208 -0.751461 -1.209858  0.637792 -1.615432  0.929646
Buket    -1.527151       NaN       NaN       NaN       NaN -0.876224
Batu      1.090813       NaN       NaN       NaN       NaN  2.193338
Rabiye   -0.385224       NaN       NaN       NaN       NaN -1.049492
Buğrahan  0.416478 -0.249212  0.066971 -0.045529 -0.425816  1.062383

In [ ]:
data.fillna(value=data.mean())

               CRP       ALT       AST         P        Na    Glukoz
Mete      0.268619 -1.361207  2.621280 -0.574841  1.067038  0.532204
Ferhat   -0.420208 -0.751461 -1.209858  0.637792 -1.615432  0.929646
Buket    -1.527151 -0.787293  0.492797  0.005808 -0.324736 -0.876224
Batu      1.090813 -0.787293  0.492797  0.005808 -0.324736  2.193338
Rabiye   -0.385224 -0.787293  0.492797  0.005808 -0.324736 -1.049492
Buğrahan  0.416478 -0.249212  0.066971 -0.045529 -0.425816  1.062383

In [ ]:
data.fillna(value=data.median())

               CRP       ALT       AST         P        Na    Glukoz
Mete      0.268619 -1.361207  2.621280 -0.574841  1.067038  0.532204
Ferhat   -0.420208 -0.751461 -1.209858  0.637792 -1.615432  0.929646
Buket    -1.527151 -0.751461  0.066971 -0.045529 -0.425816 -0.876224
Batu      1.090813 -0.751461  0.066971 -0.045529 -0.425816  2.193338
Rabiye   -0.385224 -0.751461  0.066971 -0.045529 -0.425816 -1.049492
Buğrahan  0.416478 -0.249212  0.066971 -0.045529 -0.425816  1.062383

In [ ]:
data.fillna(value=data.mean(),inplace=True)
data

               CRP       ALT       AST         P        Na    Glukoz
Mete      0.268619 -1.361207  2.621280 -0.574841  1.067038  0.532204
Ferhat   -0.420208 -0.751461 -1.209858  0.637792 -1.615432  0.929646
Buket    -1.527151 -0.787293  0.492797  0.005808 -0.324736 -0.876224
Batu      1.090813 -0.787293  0.492797  0.005808 -0.324736  2.193338
Rabiye   -0.385224 -0.787293  0.492797  0.005808 -0.324736 -1.049492
Buğrahan  0.416478 -0.249212  0.066971 -0.045529 -0.425816  1.062383

In [ ]:
data.isnull().sum()

CRP       0
ALT       0
AST       0
P         0
Na        0
Glukoz    0
dtype: int64

In [ ]:
data1=pd.DataFrame({"CRP":[1,1,2,2,3,3,5],
                    "ALT":[10,10,20,20,30,30,30],
                    "HASTALIK":["E","E","H","H","Belirsiz","Belirsiz","Belirsiz"]})
data1

   CRP  ALT  HASTALIK
0    1   10         E
1    1   10         E
2    2   20         H
3    2   20         H
4    3   30  Belirsiz
5    3   30  Belirsiz
6    5   30  Belirsiz

In [ ]:
data1.duplicated() # Veriyi ilk defa goruyorsa false ayni veriyi tekrar goruyorsa true dondurur.

0    False
1     True
2    False
3     True
4    False
5     True
6    False
dtype: bool

In [ ]:
data1=data1.drop_duplicates()
data1

   CRP  ALT  HASTALIK
0    1   10         E
2    2   20         H
4    3   30  Belirsiz
6    5   30  Belirsiz