In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.DataFrame(np.random.randn(3,3),
                  index=["hasta1","hasta2","hasta3"],
                  columns=["Glukoz","D vit","CRP"])

In [ ]:
data

          Glukoz     D vit       CRP
hasta1 -1.109612 -1.965708 -0.642845
hasta2  0.117052 -0.916387 -1.189218
hasta3  1.215855  0.655205  0.102531

In [ ]:
data.D vit

SyntaxError: invalid syntax (ipython-input-2025679540.py, line 1)

In [ ]:
data.Glukoz

hasta1   -1.109612
hasta2    0.117052
hasta3    1.215855
Name: Glukoz, dtype: float64

In [ ]:
data["D vit"]

hasta1   -1.965708
hasta2   -0.916387
hasta3    0.655205
Name: D vit, dtype: float64

In [ ]:
data[["D vit","Glukoz"]]

           D vit    Glukoz
hasta1 -1.965708 -1.109612
hasta2 -0.916387  0.117052
hasta3  0.655205  1.215855

In [ ]:
data["ALT"]=data["Glukoz"]*2

In [ ]:
data

          Glukoz     D vit       CRP       ALT
hasta1 -1.109612 -1.965708 -0.642845 -2.219223
hasta2  0.117052 -0.916387 -1.189218  0.234104
hasta3  1.215855  0.655205  0.102531  2.431711

In [ ]:
data.loc[["hasta1","hasta3"],["D vit","CRP"]]

           D vit       CRP
hasta1 -1.965708 -0.642845
hasta3  0.655205  0.102531

In [ ]:
filtre=data.CRP<0
data[filtre]

          Glukoz     D vit       CRP       ALT
hasta1 -1.109612 -1.965708 -0.642845 -2.219223
hasta2  0.117052 -0.916387 -1.189218  0.234104

In [ ]:
data[(data.CRP<0)]

          Glukoz     D vit       CRP       ALT
hasta1 -1.109612 -1.965708 -0.642845 -2.219223
hasta2  0.117052 -0.916387 -1.189218  0.234104

In [ ]:
data[(data.CRP<0) and (data["D vit"]<0)] # Pythonda "ve" islemini and ile yapiyoruz ama pandasta & sembolunu kullanmamiz gerekiyor!!

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
data[(data.CRP<0) & (data["D vit"]<0)]

          Glukoz     D vit       CRP       ALT
hasta1 -1.109612 -1.965708 -0.642845 -2.219223
hasta2  0.117052 -0.916387 -1.189218  0.234104

In [ ]:
data["P"]=np.random.rand(3) # rand randn farkina bak mutlaka!!! Baktım.
data                        # rand 0 ile 1 arasi uretir.  randn - sonsuz +sonsuz arasi uretir.

          Glukoz     D vit       CRP       ALT         P
hasta1 -1.109612 -1.965708 -0.642845 -2.219223  0.504879
hasta2  0.117052 -0.916387 -1.189218  0.234104  0.443009
hasta3  1.215855  0.655205  0.102531  2.431711  0.871808

In [ ]:
data["index"]=["i1","i2","i3"]
data["sinif"]=[1,1,0]
data

          Glukoz     D vit       CRP       ALT         P index  sinif
hasta1 -1.109612 -1.965708 -0.642845 -2.219223  0.504879    i1      1
hasta2  0.117052 -0.916387 -1.189218  0.234104  0.443009    i2      1
hasta3  1.215855  0.655205  0.102531  2.431711  0.871808    i3      0

In [ ]:
data.set_index("index",inplace=True)
data

         Glukoz     D vit       CRP       ALT         P  sinif
index
i1    -1.109612 -1.965708 -0.642845 -2.219223  0.504879      1
i2     0.117052 -0.916387 -1.189218  0.234104  0.443009      1
i3     1.215855  0.655205  0.102531  2.431711  0.871808      0

In [ ]:
data=pd.DataFrame(np.random.randn(6,6),
                  index=["hasta1","hasta2","hasta3","hasta4","hasta5","hasta6"],
                  columns=["Glukoz","D vit","CRP","ALT","P","Na"])
data.loc["hasta3":"hasta5",["D vit","P"]]=np.nan
data

          Glukoz     D vit       CRP       ALT         P        Na
hasta1 -1.249420  0.292781  0.349718  1.341680 -0.416247 -0.000564
hasta2 -1.157624 -0.932499  1.916500 -0.440911 -0.304808 -1.796773
hasta3  0.826707       NaN  1.627603 -0.712861       NaN  0.406454
hasta4  2.601879       NaN  1.847740 -1.652595       NaN -0.274707
hasta5 -0.395487       NaN -0.949481 -0.621698       NaN -0.667184
hasta6  1.076567  0.412855 -0.158378  0.409750  0.717718 -0.261402

In [ ]:
data.isnull().sum()

Glukoz    0
D vit     3
CRP       0
ALT       0
P         3
Na        0
dtype: int64

In [ ]:
data.isnull().sum().sum()

np.int64(6)

In [ ]:
data.dropna(axis=1) # NaN deger varsa o sutunları komple cikarir.

          Glukoz       CRP       ALT        Na
hasta1 -1.249420  0.349718  1.341680 -0.000564
hasta2 -1.157624  1.916500 -0.440911 -1.796773
hasta3  0.826707  1.627603 -0.712861  0.406454
hasta4  2.601879  1.847740 -1.652595 -0.274707
hasta5 -0.395487 -0.949481 -0.621698 -0.667184
hasta6  1.076567 -0.158378  0.409750 -0.261402

In [ ]:
data.dropna(axis=0) # NaN deger varsa o satirlari komple cikarir.

          Glukoz     D vit       CRP       ALT         P        Na
hasta1 -1.249420  0.292781  0.349718  1.341680 -0.416247 -0.000564
hasta2 -1.157624 -0.932499  1.916500 -0.440911 -0.304808 -1.796773
hasta6  1.076567  0.412855 -0.158378  0.409750  0.717718 -0.261402

In [ ]:
data

          Glukoz     D vit       CRP       ALT         P        Na
hasta1 -1.249420  0.292781  0.349718  1.341680 -0.416247 -0.000564
hasta2 -1.157624 -0.932499  1.916500 -0.440911 -0.304808 -1.796773
hasta3  0.826707       NaN  1.627603 -0.712861       NaN  0.406454
hasta4  2.601879       NaN  1.847740 -1.652595       NaN -0.274707
hasta5 -0.395487       NaN -0.949481 -0.621698       NaN -0.667184
hasta6  1.076567  0.412855 -0.158378  0.409750  0.717718 -0.261402

In [ ]:
def OrtalamaIleDoldur(data):
  toplam=data.sum().sum()  # Data daki verilerin hepsini toplar.
  elemanSayisi=data.size-data.isnull().sum().sum()  # Data boyutu (6*6) - data daki NaN degerler (6)
  ortalama=toplam/elemanSayisi
  return ortalama

In [ ]:
data.fillna(OrtalamaIleDoldur(data))

          Glukoz     D vit       CRP       ALT         P        Na
hasta1 -1.249420  0.292781  0.349718  1.341680 -0.416247 -0.000564
hasta2 -1.157624 -0.932499  1.916500 -0.440911 -0.304808 -1.796773
hasta3  0.826707  0.061177  1.627603 -0.712861  0.061177  0.406454
hasta4  2.601879  0.061177  1.847740 -1.652595  0.061177 -0.274707
hasta5 -0.395487  0.061177 -0.949481 -0.621698  0.061177 -0.667184
hasta6  1.076567  0.412855 -0.158378  0.409750  0.717718 -0.261402

In [ ]:
data.mean(skipna=True)  # O sutundaki NaN olmayan butun verileri toplar ve NaN olmayan eleman sayisina boler.
# skipna=True NaN degerleri atlamamizi saglar.

Glukoz    0.283770
D vit    -0.075621
CRP       0.772284
ALT      -0.279439
P        -0.001112
Na       -0.432363
dtype: float64

In [ ]:
data.mean(skipna=False) # Eger sutunda tek bir tane bile NaN varsa ortalama NaN doner.

Glukoz    0.283770
D vit          NaN
CRP       0.772284
ALT      -0.279439
P              NaN
Na       -0.432363
dtype: float64

In [ ]:
data.mean() # skipna=True yazmasanda ayni sonucu aliriz. skipna=True ile..

Glukoz    0.283770
D vit    -0.075621
CRP       0.772284
ALT      -0.279439
P        -0.001112
Na       -0.432363
dtype: float64

In [ ]:
data.mean(axis=1) # Satir bazinda ortalama alir.

hasta1    0.052991
hasta2   -0.452686
hasta3    0.536976
hasta4    0.630579
hasta5   -0.658463
hasta6    0.366185
dtype: float64

In [ ]:
data.mean().mean() # Ortalama ortalamasi

np.float64(0.04458650446709747)

In [ ]:
data.fillna(value=data.mean(skipna=True))

          Glukoz     D vit       CRP       ALT         P        Na
hasta1 -1.249420  0.292781  0.349718  1.341680 -0.416247 -0.000564
hasta2 -1.157624 -0.932499  1.916500 -0.440911 -0.304808 -1.796773
hasta3  0.826707 -0.075621  1.627603 -0.712861 -0.001112  0.406454
hasta4  2.601879 -0.075621  1.847740 -1.652595 -0.001112 -0.274707
hasta5 -0.395487 -0.075621 -0.949481 -0.621698 -0.001112 -0.667184
hasta6  1.076567  0.412855 -0.158378  0.409750  0.717718 -0.261402

In [ ]:
data = pd.read_csv("../data/raw/eksikveriler2.csv")
data

   eegkanal  frekans  genlik   yas hasta
0     F3-C3      130      30  10.0     e
1     F3-C3      125      36  11.0     e
2     F3-C3      135      34  10.0     h
3     F3-C3      133      30   9.0     h
4     F3-C3      129      38  12.0     e
5     F3-C3      180      90  30.0     e
6     F3-C3      190      80  25.0     e
7     F3-C3      175      90  35.0     e
8     F3-C3      177      60  22.0     h
9     F4-C4      185     105  33.0     e
10    F4-C4      165      55  27.0     h
11    F4-C4      155      50  44.0     h
12    F4-C4      160      58   NaN     h
13    F4-C4      162      59  41.0     h
14    F4-C4      167      62  55.0     h
15    T4-T6      174      70  47.0     e
16    T4-T6      193      90   NaN     e
17    T4-T6      187      80  27.0     e
18    T4-T6      183      88  28.0     e
19    T4-T6      159      40  29.0     h
20    T4-T6      164      66  32.0     h
21    T4-T6      166      56  42.0     h

In [ ]:
data.head()

  eegkanal  frekans  genlik   yas hasta
0    F3-C3      130      30  10.0     e
1    F3-C3      125      36  11.0     e
2    F3-C3      135      34  10.0     h
3    F3-C3      133      30   9.0     h
4    F3-C3      129      38  12.0     e

In [ ]:
data.tail()

   eegkanal  frekans  genlik   yas hasta
17    T4-T6      187      80  27.0     e
18    T4-T6      183      88  28.0     e
19    T4-T6      159      40  29.0     h
20    T4-T6      164      66  32.0     h
21    T4-T6      166      56  42.0     h

In [ ]:
data.columns

Index(['eegkanal', 'frekans', 'genlik', 'yas', 'hasta'], dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   eegkanal  22 non-null     object
 1   frekans   22 non-null     int64
 2   genlik    22 non-null     int64
 3   yas       20 non-null     float64
 4   hasta     22 non-null     object
dtypes: float64(1), int64(2), object(2)
memory usage: 1012.0+ bytes

In [ ]:
data.describe().T

         count        mean        std    min    25%    50%     75%    max
frekans   22.0  163.363636  21.077059  125.0  156.0  165.5  179.25  193.0
genlik    22.0   62.136364  22.286651   30.0   42.5   59.5   80.00  105.0
yas       20.0   28.450000  13.382923    9.0   19.5   28.5   36.50   55.0

In [ ]:
data.shape

(22, 5)

In [ ]:
data.isnull().sum()

eegkanal    0
frekans     0
genlik      0
yas         2
hasta       0
dtype: int64

In [ ]:
data

   eegkanal  frekans  genlik   yas hasta
0     F3-C3      130      30  10.0     e
1     F3-C3      125      36  11.0     e
2     F3-C3      135      34  10.0     h
3     F3-C3      133      30   9.0     h
4     F3-C3      129      38  12.0     e
5     F3-C3      180      90  30.0     e
6     F3-C3      190      80  25.0     e
7     F3-C3      175      90  35.0     e
8     F3-C3      177      60  22.0     h
9     F4-C4      185     105  33.0     e
10    F4-C4      165      55  27.0     h
11    F4-C4      155      50  44.0     h
12    F4-C4      160      58   NaN     h
13    F4-C4      162      59  41.0     h
14    F4-C4      167      62  55.0     h
15    T4-T6      174      70  47.0     e
16    T4-T6      193      90   NaN     e
17    T4-T6      187      80  27.0     e
18    T4-T6      183      88  28.0     e
19    T4-T6      159      40  29.0     h
20    T4-T6      164      66  32.0     h
21    T4-T6      166      56  42.0     h

In [ ]:
frekansGenlikYas=data.iloc[:,1:4] # 1,2 ve 3 indexli sutunlari alir yani frekans,genlik,yas sutunlari alinir.
frekansGenlikYas

    frekans  genlik   yas
0       130      30  10.0
1       125      36  11.0
2       135      34  10.0
3       133      30   9.0
4       129      38  12.0
5       180      90  30.0
6       190      80  25.0
7       175      90  35.0
8       177      60  22.0
9       185     105  33.0
10      165      55  27.0
11      155      50  44.0
12      160      58   NaN
13      162      59  41.0
14      167      62  55.0
15      174      70  47.0
16      193      90   NaN
17      187      80  27.0
18      183      88  28.0
19      159      40  29.0
20      164      66  32.0
21      166      56  42.0

In [ ]:
from sklearn.impute import SimpleImputer  # NaN degerleri doldurmak icin kullanilan kutuphanedir.
eksikVeriTamamlama=SimpleImputer(missing_values=np.nan,strategy="mean") # missing_values=np.nan NaN verileri doldurcak. strategy="mean" eksik verileri sutun ortalamasiyla doldurur. Bu satirda eksikler doldurulmuyor.
eksikVeriTamamlama=eksikVeriTamamlama.fit(data.iloc[:,1:4]) # fit ile NaN olmayan degerlerin ortalamasi hesaplanir hafizada tutulur.
data.iloc[:,1:4] = eksikVeriTamamlama.transform(data.iloc[:,1:4]) # transform fit'i kullanarak NaN'lari doldurur.
data

   eegkanal  frekans  genlik    yas hasta
0     F3-C3      130      30  10.00     e
1     F3-C3      125      36  11.00     e
2     F3-C3      135      34  10.00     h
3     F3-C3      133      30   9.00     h
4     F3-C3      129      38  12.00     e
5     F3-C3      180      90  30.00     e
6     F3-C3      190      80  25.00     e
7     F3-C3      175      90  35.00     e
8     F3-C3      177      60  22.00     h
9     F4-C4      185     105  33.00     e
10    F4-C4      165      55  27.00     h
11    F4-C4      155      50  44.00     h
12    F4-C4      160      58  28.45     h
13    F4-C4      162      59  41.00     h
14    F4-C4      167      62  55.00     h
15    T4-T6      174      70  47.00     e
16    T4-T6      193      90  28.45     e
17    T4-T6      187      80  27.00     e
18    T4-T6      183      88  28.00     e
19    T4-T6      159      40  29.00     h
20    T4-T6      164      66  32.00     h
21    T4-T6      166      56  42.00     h

In [ ]:
data = pd.read_csv("../data/raw/eksikveriler2.csv")

from sklearn.impute import SimpleImputer
eksikVeriTamamlama=SimpleImputer(missing_values=np.nan,strategy="median") # Medyanla doldurur.
eksikVeriTamamlama=eksikVeriTamamlama.fit(data.iloc[:,1:4])
data.iloc[:,1:4] = eksikVeriTamamlama.transform(data.iloc[:,1:4])
data

   eegkanal  frekans  genlik   yas hasta
0     F3-C3      130      30  10.0     e
1     F3-C3      125      36  11.0     e
2     F3-C3      135      34  10.0     h
3     F3-C3      133      30   9.0     h
4     F3-C3      129      38  12.0     e
5     F3-C3      180      90  30.0     e
6     F3-C3      190      80  25.0     e
7     F3-C3      175      90  35.0     e
8     F3-C3      177      60  22.0     h
9     F4-C4      185     105  33.0     e
10    F4-C4      165      55  27.0     h
11    F4-C4      155      50  44.0     h
12    F4-C4      160      58  28.5     h
13    F4-C4      162      59  41.0     h
14    F4-C4      167      62  55.0     h
15    T4-T6      174      70  47.0     e
16    T4-T6      193      90  28.5     e
17    T4-T6      187      80  27.0     e
18    T4-T6      183      88  28.0     e
19    T4-T6      159      40  29.0     h
20    T4-T6      164      66  32.0     h
21    T4-T6      166      56  42.0     h

In [ ]:
data = pd.read_csv("../data/raw/eksikveriler2.csv")

from sklearn.impute import SimpleImputer
eksikVeriTamamlama=SimpleImputer(missing_values=np.nan,strategy="most_frequent") # En sik gorulen deger ile doldurur.
eksikVeriTamamlama=eksikVeriTamamlama.fit(data.iloc[:,1:4])
data.iloc[:,1:4] = eksikVeriTamamlama.transform(data.iloc[:,1:4])
data

   eegkanal  frekans  genlik   yas hasta
0     F3-C3      130      30  10.0     e
1     F3-C3      125      36  11.0     e
2     F3-C3      135      34  10.0     h
3     F3-C3      133      30   9.0     h
4     F3-C3      129      38  12.0     e
5     F3-C3      180      90  30.0     e
6     F3-C3      190      80  25.0     e
7     F3-C3      175      90  35.0     e
8     F3-C3      177      60  22.0     h
9     F4-C4      185     105  33.0     e
10    F4-C4      165      55  27.0     h
11    F4-C4      155      50  44.0     h
12    F4-C4      160      58  10.0     h
13    F4-C4      162      59  41.0     h
14    F4-C4      167      62  55.0     h
15    T4-T6      174      70  47.0     e
16    T4-T6      193      90  10.0     e
17    T4-T6      187      80  27.0     e
18    T4-T6      183      88  28.0     e
19    T4-T6      159      40  29.0     h
20    T4-T6      164      66  32.0     h
21    T4-T6      166      56  42.0     h

In [ ]:
data = pd.read_csv("../data/raw/eksikveriler2.csv")

from sklearn.impute import SimpleImputer
eksikVeriTamamlama=SimpleImputer(missing_values=np.nan,strategy="constant", fill_value=40) # Belirli bir sabit deger ile doldurur.
eksikVeriTamamlama=eksikVeriTamamlama.fit(data.iloc[:,1:4])
data.iloc[:,1:4] = eksikVeriTamamlama.transform(data.iloc[:,1:4])
data

   eegkanal  frekans  genlik   yas hasta
0     F3-C3      130      30  10.0     e
1     F3-C3      125      36  11.0     e
2     F3-C3      135      34  10.0     h
3     F3-C3      133      30   9.0     h
4     F3-C3      129      38  12.0     e
5     F3-C3      180      90  30.0     e
6     F3-C3      190      80  25.0     e
7     F3-C3      175      90  35.0     e
8     F3-C3      177      60  22.0     h
9     F4-C4      185     105  33.0     e
10    F4-C4      165      55  27.0     h
11    F4-C4      155      50  44.0     h
12    F4-C4      160      58  40.0     h
13    F4-C4      162      59  41.0     h
14    F4-C4      167      62  55.0     h
15    T4-T6      174      70  47.0     e
16    T4-T6      193      90  40.0     e
17    T4-T6      187      80  27.0     e
18    T4-T6      183      88  28.0     e
19    T4-T6      159      40  29.0     h
20    T4-T6      164      66  32.0     h
21    T4-T6      166      56  42.0     h

In [ ]:
data.hasta.value_counts()  # hasta sutununda hangi gruplar varsa sayisini verir.

hasta
e    11
h    11
Name: count, dtype: int64

In [ ]:
data.eegkanal.value_counts()

eegkanal
F3-C3    9
T4-T6    7
F4-C4    6
Name: count, dtype: int64

In [ ]:
hastalik=data.iloc[:,-1].values  # Son sutunu gosterir.
hastalik

array(['e', 'e', 'h', 'h', 'e', 'e', 'e', 'e', 'h', 'e', 'h', 'h', 'h',
       'h', 'h', 'e', 'e', 'e', 'e', 'h', 'h', 'h'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder # 0 1 e ceviren kutuphane
le=LabelEncoder() # Alfabetik olarak baslar. Alfabede once gelene 0 sonra 1 2 diye devam eder.
hastalik=data.iloc[:,-1].values
hastalik=le.fit_transform(hastalik)
hastalik

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   eegkanal  22 non-null     object
 1   frekans   22 non-null     int64
 2   genlik    22 non-null     int64
 3   yas       22 non-null     float64
 4   hasta     22 non-null     object
dtypes: float64(1), int64(2), object(2)
memory usage: 1012.0+ bytes

In [ ]:
dfHastalik=pd.DataFrame(data=hastalik,index=range(22),columns=["Hastalik"]) # index=range(22) 0dan baslar 21de biter.
dfHastalik

    Hastalik
0          0
1          0
2          1
3          1
4          0
5          0
6          0
7          0
8          1
9          0
10         1
11         1
12         1
13         1
14         1
15         0
16         0
17         0
18         0
19         1
20         1
21         1

In [ ]:
eeg=data.iloc[:,0:1].values
eeg
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
eeg[:,0]=le.fit_transform(data.iloc[:,0:1])
eeg

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2]], dtype=object)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
eeg=ohe.fit_transform(data.iloc[:,0:1]).toarray()
eeg

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [ ]:
dfEEG=pd.DataFrame(data=eeg,index=range(22),columns=["F3-C3","T4-T6","F4-C4"])
dfEEG

    F3-C3  T4-T6  F4-C4
0     1.0    0.0    0.0
1     1.0    0.0    0.0
2     1.0    0.0    0.0
3     1.0    0.0    0.0
4     1.0    0.0    0.0
5     1.0    0.0    0.0
6     1.0    0.0    0.0
7     1.0    0.0    0.0
8     1.0    0.0    0.0
9     0.0    1.0    0.0
10    0.0    1.0    0.0
11    0.0    1.0    0.0
12    0.0    1.0    0.0
13    0.0    1.0    0.0
14    0.0    1.0    0.0
15    0.0    0.0    1.0
16    0.0    0.0    1.0
17    0.0    0.0    1.0
18    0.0    0.0    1.0
19    0.0    0.0    1.0
20    0.0    0.0    1.0
21    0.0    0.0    1.0

In [ ]:
frekansGenlikYas=data.iloc[:,1:4].values
frekansGenlikYas

dffrekansGenlikYas=pd.DataFrame(data=frekansGenlikYas,
                                index=range(22),
                                columns=["Frekans","Genlik","Yas"])
dffrekansGenlikYas

    Frekans  Genlik   Yas
0     130.0    30.0  10.0
1     125.0    36.0  11.0
2     135.0    34.0  10.0
3     133.0    30.0   9.0
4     129.0    38.0  12.0
5     180.0    90.0  30.0
6     190.0    80.0  25.0
7     175.0    90.0  35.0
8     177.0    60.0  22.0
9     185.0   105.0  33.0
10    165.0    55.0  27.0
11    155.0    50.0  44.0
12    160.0    58.0  40.0
13    162.0    59.0  41.0
14    167.0    62.0  55.0
15    174.0    70.0  47.0
16    193.0    90.0  40.0
17    187.0    80.0  27.0
18    183.0    88.0  28.0
19    159.0    40.0  29.0
20    164.0    66.0  32.0
21    166.0    56.0  42.0

In [ ]:
dataSon=pd.concat([dfEEG,dffrekansGenlikYas,dfHastalik],axis=1) # Olusturduklarimizi birlestirdik.
dataSon

    F3-C3  T4-T6  F4-C4  Frekans  Genlik   Yas  Hastalik
0     1.0    0.0    0.0    130.0    30.0  10.0         0
1     1.0    0.0    0.0    125.0    36.0  11.0         0
2     1.0    0.0    0.0    135.0    34.0  10.0         1
3     1.0    0.0    0.0    133.0    30.0   9.0         1
4     1.0    0.0    0.0    129.0    38.0  12.0         0
5     1.0    0.0    0.0    180.0    90.0  30.0         0
6     1.0    0.0    0.0    190.0    80.0  25.0         0
7     1.0    0.0    0.0    175.0    90.0  35.0         0
8     1.0    0.0    0.0    177.0    60.0  22.0         1
9     0.0    1.0    0.0    185.0   105.0  33.0         0
10    0.0    1.0    0.0    165.0    55.0  27.0         1
11    0.0    1.0    0.0    155.0    50.0  44.0         1
12    0.0    1.0    0.0    160.0    58.0  40.0         1
13    0.0    1.0    0.0    162.0    59.0  41.0         1
14    0.0    1.0    0.0    167.0    62.0  55.0         1
15    0.0    0.0    1.0    174.0    70.0  47.0         0
16    0.0    0.0    1.0    193.0    90.0  40.0         0
17    0.0    0.0    1.0    187.0    80.0  27.0         0
18    0.0    0.0    1.0    183.0    88.0  28.0         0
19    0.0    0.0    1.0    159.0    40.0  29.0         1
20    0.0    0.0    1.0    164.0    66.0  32.0         1
21    0.0    0.0    1.0    166.0    56.0  42.0         1

In [ ]:
dataSon.to_csv("dataSon.csv",index=False,encoding="utf-8") # Bu sekilde de csv uzantili yeni dosyamizi olusturduk indirebiliriz dosyalar kismindan.